### ISSUE TITLE
How can I get a image's camera parameters, thanks.

### ISSUE THREAD

**Issue by testouya** [oneThousand1000/EG3D-projector#1]
Hello,
I want to run the code, but the picture I used is something downloaded from internet,
I dont known its camera parameters, and I dont known the parameters' s format.
How can I get a random image's camera parameters, thanks.

**Comment by oneThousand1000** [comment]
> Hello, I want to run the code, but the picture I used is something downloaded from internet, I dont known its camera parameters, and I dont known the parameters' s format. How can I get a random image's camera parameters, thanks.

See https://github.com/NVlabs/eg3d/issues/18#issuecomment-1200366872

**Comment by testouya** [comment]
Thanks a lot, I will see.
