### ISSUE TITLE
image_id How is .npy converted?

### ISSUE THREAD

**Issue by willis** [oneThousand1000/EG3D-projector#14]
Pass PTI？Have a script?

**Comment by oneThousand1000** [comment]
Please refer to https://github.com/oneThousand1000/EG3D-projector/issues/1 and https://github.com/oneThousand1000/EG3D-projector/issues/9

**Comment by willis** [comment]
**eg3d run preprocess_in_the_wild.py , dataset.json**
{"labels": [["0051.png", [0.9781659841537476, -0.0015946876956149936, -0.20781905949115753, 0.5311063375845698, -0.018268808722496033, -0.9967593550682068, -0.0783393383026123, 0.2065786134229804, -0.20702067017555237, 0.08042547851800919, -0.9750252366065979, 2.639176260626362, 0.0, 0.0, 0.0, 1.0, 4.2647, 0.0, 0.5, 0.0, 4.2647, 0.5, 0.0, 0.0, 1.0]], ["0051_mirror.png", [0.9781659841537476, 0.0015946876956149936, 0.20781905949115753, -0.5311063375845698, 0.018268808722496033, -0.9967593550682068, -0.0783393383026123, 0.2065786134229804, 0.20702067017555237, 0.08042547851800919, -0.9750252366065979, 2.639176260626362, 0.0, 0.0, 0.0, 1.0, 4.2647, 0.0, 0.5, 0.0, 4.2647, 0.5, 0.0, 0.0, 1.0]]]}

**python converted**
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--path', type=str, required=True)
    parser.add_argument('--name', type=str, required=True)
    args = parser.parse_args()

    with open(os.path.join(args.path, args.name+'.json')) as f:
        cameras = json.load(f)

    np.save(os.path.join(args.path, args.name+'.npy'),cameras)


**run run_projector.py is error**

(eg3d) E:\git\EG3D-projector\eg3d>python run_projector.py --outdir=projector_out --latent_space_type w  --network=networks/ffhq512-128.pkl --sample_mult=2  --image_path ./projector_test_data/0051.png --c_path ./projector_test_data/0051.npy
Loading networks from "networks/ffhq512-128.pkl"...
Traceback (most recent call last):
  File "run_projector.py", line 148, in <module>
    run()  # pylint: disable=no-value-for-parameter
  File "C:\ProgramData\Anaconda3\envs\eg3d\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\eg3d\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\envs\eg3d\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\envs\eg3d\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "run_projector.py", line 115, in run
    c = np.load(c_path)
  File "C:\ProgramData\Anaconda3\envs\eg3d\lib\site-packages\numpy\lib\npyio.py", line 432, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "C:\ProgramData\Anaconda3\envs\eg3d\lib\site-packages\numpy\lib\format.py", line 787, in read_array
    raise ValueError("Object arrays cannot be loaded when "
ValueError: Object arrays cannot be loaded when allow_pickle=False
