### ISSUE TITLE
w and w_plus latent code

### ISSUE THREAD

**Issue by HarukiYqM** [oneThousand1000/EG3D-projector#15]
Thank you so much for sharing this code!

Ihave a small question about the use of w and w_plus latent. I found in the gen_video script, it seems that you did not distinguish w between w_plus latent and feed them to G all as ws. Is that correct?

**Comment by oneThousand1000** [comment]
Hi HarukiYqM,
Yes, I did not distinguish w between w_plus, because w is repeated to be the same shape as w_plus, so you can feed them to G in the same way. 

See https://github.com/oneThousand1000/EG3D-projector/blob/5f0340caf47c9c8d1079eac02f7044fb52ca5abb/eg3d/projector/w_projector.py#L176, on this line the w is repeated.

**Comment by HarukiYqM** [comment]
That makes sense. 

Thanks a lot for your quick response :)

**Comment by HarukiYqM** [comment]
I have a followup question that, for the command of gen_video, why did you still use trunc 0.7 for ws? To my understanding, the projected w or w_plus should be optimal and no need to interp with w_avg.

**Comment by oneThousand1000** [comment]
Hi! 
Actually, the truncation is performed in the mapping network of the Stylegan backbone, see
https://github.com/oneThousand1000/EG3D-projector/blob/5f0340caf47c9c8d1079eac02f7044fb52ca5abb/eg3d/training/networks_stylegan2.py#L260

You can see in my [video generation code](https://github.com/oneThousand1000/EG3D-projector/blob/master/eg3d/gen_videos_from_given_latent_code.py), I did not use the mapping network and truncation_psi, but directly input w/w+ to synthesis network. 

I think I just forget to delete the `--trunc=0.7` option in the readme, will update it. ;)

**Comment by HarukiYqM** [comment]
Oh I see. Thanks!
