### ISSUE TITLE
Some questions about latent code and finetune

### ISSUE THREAD

**Issue by stickice** [oneThousand1000/EG3D-projector#16]
Thanks for your great! I'm new to research. And I learnt a a lot from the code. But I still have some questions. 
1. In fact, I noticed that eg3d did not release the inversion code, so I tried to inversion using PTI. However, I found the latent code produced by PTI original project is `1,18,512`. But eg3d need `1,14.512`. I was stuck. I learnt that you change the code here so that it can produce `1,14,512` latent code. 
https://github.com/oneThousand1000/EG3D-projector/blob/a9c61920b5f127a2c9eba68cab7b7fc7bacf9274/eg3d/projector/w_projector.py#L176
Is it mean that I can produce any size latent code by change the code? And I have observed the latent code. Although it is `1,14,512`. It seems that the middle 14 dims have same data. 
`tensor([[[-0.4189,  0.0661,  0.0754,  ...,  0.2367,  0.0928,  0.3013],
         [-0.4189,  0.0661,  0.0754,  ...,  0.2367,  0.0928,  0.3013],
         ...,
         [-0.4189,  0.0661,  0.0754,  ...,  0.2367,  0.0928,  0.3013],
         [-0.4189,  0.0661,  0.0754,  ...,  0.2367,  0.0928,  0.3013]]])`I do not know why.
2. I also confused why finetune the eg3d model using images can improve the performance.
![seed0](https://user-images.githubusercontent.com/58260662/233679353-8e23ea42-69ac-445f-98e5-ffd81bb77ccf.png)
![seed5](https://user-images.githubusercontent.com/58260662/233679361-642623de-2551-44bb-a8f2-a37821dc06ec.png)
After finetune, there are more details. I am confused because eg3d was trained on these images. Why these images can improve its performance?
3. The last question is that I have a little problem when finetune the model. I run the script on a 4 GPUs pc. So I change the config of PTI. 
https://github.com/oneThousand1000/EG3D-projector/blob/a9c61920b5f127a2c9eba68cab7b7fc7bacf9274/eg3d/projector/PTI/configs/global_config.py#L2
https://github.com/oneThousand1000/EG3D-projector/blob/a9c61920b5f127a2c9eba68cab7b7fc7bacf9274/eg3d/projector/PTI/configs/global_config.py#L3
I want to run on the second gpu. I change the code to `cuda_visible_devices = '4'
device = 'cuda:1'`. However it reported error `RuntimeError: No CUDA GPUs are available`. Only `cuda_visible_devices = '0'
device = 'cuda:0'` can run the script. Have you ever seen this problem?

I'd appreciate it if I can get your instruction. Thanks again!

**Comment by oneThousand1000** [comment]
Hi stickice,

1. eg3d needs [1,14.512] w+ latent code, because eg3d's stylegan backbone generates 256x256 feature maps (please refer to the eg3d and stylegan paper). 
w_opt is actually the w latent code with the shape of [1, 1, 512] (please refer to the stylegan paper), and I just repeat the second dim 14 times. 
2. This is caused by the limited expression power of eg3d. Please refer to the PTI paper for more details.  
3. This project is only achieved on a single GPU. 

For the 1 and 2, I strongly recommend you to read the paper of stylegan (http://arxiv.org/abs/1812.04948), PTI (http://arxiv.org/abs/2106.05744), and eg3d (http://arxiv.org/abs/2112.07945) first.

**Comment by stickice** [comment]
Thanks a lot for your quick response!

**Comment by stickice** [comment]
Hi, sorry for reopening the issue. I have some problem when I use [preprocess_in_the_wild.py](https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_in_the_wild.py) to preprocess some in-the-wild images of ffhq dataset. After running the script, I got cropped images but they are not correctly aligned. 
![00018](https://user-images.githubusercontent.com/58260662/233789254-0bbd520b-fdb8-4f2b-8b3a-f959f29a71e8.png)
![00018（复件）](https://user-images.githubusercontent.com/58260662/233789319-137791cf-6979-423c-9c28-b6f9fd3833ff.png)
During running `preprocess_in_the_wild.py`, running `test.py` part reports error. Other parts run correctly. Does it affect the final results?

**Comment by oneThousand1000** [comment]
Please open a issue in eg3d repo.

**Comment by oneThousand1000** [comment]
For the "not correctly aligned", see https://github.com/NVlabs/eg3d/issues/28#issuecomment-1200381552

**Comment by stickice** [comment]
Thanks for your reply!
