### ISSUE TITLE
About get image_id.npy file, thanks

### ISSUE THREAD

**Issue by testouya** [oneThousand1000/EG3D-projector#4]
Hello,
I want to get image_id.npy from image_id.png.
these are what I do:
1) put image_id.png in **/home/username/EG3D-projector/eg3d/projector_test_data** dir.
2) git clone NVlabs/eg3d
3) cd **/home/username/eg3d/dataset_preprocessing/ffhq**/
4) run cmd : python preprocess_in_the_wild.py --indir=/home/username/EG3D-projector/eg3d/projector_test_data

It tell me 'No such file or directory: 'Deep3DFaceRecon_pytorch'
1) I use git clone Deep3DFaceRecon_pytorch  from https://github.com/sicxu/Deep3DFaceRecon_pytorch, 
and save it to /home/username/eg3d/dataset_preprocessing/ffhq/Deep3DFaceRecon_pytorch

2) run  **python preprocess_in_the_wild.py --indir=/home/username/EG3D-projector/eg3d/projector_test_data**  again

but It tell me:
File "/home/username/eg3d/dataset_preprocessing/ffhq/Deep3DFaceRecon_pytorch/models/networks.py", line 18, in <module>
    from .arcface_torch.backbones import get_model
ModuleNotFoundError: No module named 'models.arcface_torch'

where is the arcface_torch module ?
**from .arcface_torch.backbones import get_model**

Is my operator right?
thanks.

**Comment by oneThousand1000** [comment]
Please finish all the [installation](https://github.com/sicxu/Deep3DFaceRecon_pytorch#installation) steps in Deep3DFaceRecon_pytorch.

Install Arcface Pytorch:
```
cd ..    # ./Deep3DFaceRecon_pytorch
git clone https://github.com/deepinsight/insightface.git
cp -r ./insightface/recognition/arcface_torch ./models/
```

**Comment by testouya** [comment]
thank a lot!
