### ISSUE TITLE
A new problem about getting image_id.npy file, thanks

### ISSUE THREAD

**Issue by testouya** [oneThousand1000/EG3D-projector#5]
I put a image_id.png file in **/home/username/EG3D-projector/eg3d/projector_test_data**
and want to  run cmd **python preprocess_in_the_wild.py --indir=/home/username/EG3D-projector/eg3d/projector_test_data**
to get image_id.npy file.

before this step,
I have installed Deep3DFaceRecon_pytorch's dependency.

but when I run this cmd, something error occured:

++++++++++++++++++++++++++++++++
0 /home/xxxx/eg3d/EG3D-projector/eg3d/projector_test_data/jia.png
create glctx on device cuda:0
**python 3dface2idr_mat.py --in_root Deep3DFaceRecon_pytorch/checkpoints/pretrained/results/epoch_20_000000**
Traceback (most recent call last):
  File "/home/xxxx/eg3d/eg3d/dataset_preprocessing/ffhq/3dface2idr_mat.py", line 27, in <module>
    npys = sorted([x for x in os.listdir(in_root) if x.endswith(".mat")])
FileNotFoundError: [Errno 2] No such file or directory: 'Deep3DFaceRecon_pytorch/checkpoints/pretrained/results/epoch_20_000000'
python preprocess_cameras.py --source Deep3DFaceRecon_pytorch/checkpoints/pretrained/results/epoch_20_000000 --mode orig
Traceback (most recent call last):
  File "/home/xxxx/eg3d/eg3d/dataset_preprocessing/ffhq/preprocess_cameras.py", line 80, in <module>
    with open(camera_dataset_file, "r") as f:
FileNotFoundError: [Errno 2] **No such file or directory: 'Deep3DFaceRecon_pytorch/checkpoints/pretrained/results/epoch_20_000000/cameras.json'**
++++++++++++++++++++++++++++++++

I found Deep3DFaceRecon_pytorch had created a obj model from the image_id.png file,
but It is not the final model.

How can I get the cameras.json ?

Thanks very much.

**Comment by oneThousand1000** [comment]
Hi, you should make some modifications.

In preprocess_in_the_wild.py, please place the 'Deep3DFaceRecon_pytorch/checkpoints/pretrained/results/' with your own args.indir.

**Comment by oneThousand1000** [comment]
And cameras.json will be saved to f'{args.indir}/epoch_20_000000/cameras.json', so please make sure the dir f'{args.indir}/epoch_20_000000' exists (may be you can create one using os.makedirs).

For more information, Please create an issue in [eg3d](https://github.com/NVlabs/eg3d)

**Comment by testouya** [comment]
thanks very much, 
I run **mkdir** by manual, create **{args.indir}/epoch_20_000000** directory
re-run python cmd, and no error occured. 
This time, I found cameras.json file.

but I didnt find image_id.npy file.
should I run some other cmd to generate it?

**Comment by testouya** [comment]
> The camera parameters is stored in dataset.json (it is saved in the same dir as camera.json), you just need to save the camera parameters in dataset.json to a npy file

how to save?
run linux shell cmd:
**mv dataset.json image_id.npy**  ?

thanks , I will try.

**Comment by oneThousand1000** [comment]
Read the json file then np.save

**Comment by testouya** [comment]
> Or you can directly read camera parameters from dataset.json, the npy file is not necessary.

re-run python preprocess_in_the_wild.py --indir=/home/username/EG3D-projector/eg3d/projector_test_data
cmd.

no error occured.

I got image_id.obj model file (generated by Deep3DFaceRecon_pytorch)

I got **cameras.json** and **dataset.json** file,

but there's no data in the two files.

run linux shell cmd:
cat cameras.json
**{}**

cat dataset.json
**{
    "labels": []
}**

Is something wrong with my operator?

thanks.

**Comment by testouya** [comment]
> Read the json file then np.save

thanks ,this is the picture I used.
https://gss0.baidu.com/9fo3dSag_xI4khGko9WTAnF6hhy/zhidao/pic/item/7c1ed21b0ef41bd57f7f20ff57da81cb39db3d89.jpg

**Comment by testouya** [comment]
问下啊，这个原理是啥，
微软的 deepface只生成基本脸型，没有头发，脖子后脑勺，

这个开源项目是能把剩余的建出来？

这个项目对脸型还会做调整吗？
多谢。

**Comment by oneThousand1000** [comment]
Deep3DFaceRecon_pytorch is used to extract the camera parameters from input images.

Then the camera parameters and image are fed into eg3d projector to get its corresponding latent code (GAN inversion).

**Comment by testouya** [comment]
> > Or you can directly read camera parameters from dataset.json, the npy file is not necessary.
> 
> re-run python preprocess_in_the_wild.py --indir=/home/username/EG3D-projector/eg3d/projector_test_data cmd.
> 
> no error occured.
> 
> I got image_id.obj model file (generated by Deep3DFaceRecon_pytorch)
> 
> I got **cameras.json** and **dataset.json** file,
> 
> but there's no data in the two files.
> 
> run linux shell cmd: cat cameras.json **{}**
> 
> cat dataset.json **{ "labels": [] }**
> 
> Is something wrong with my operator?
> 
> thanks.

搞定了，想从mat文件里读数据，进而生成json，结果路径搞错了，mat文件没找到。
改成正确路径，就生成了。
