### ISSUE TITLE
代码运行完毕，无报错，但是为何找不到输出的三维模型，谢谢。

### ISSUE THREAD

**Issue by testouya** [oneThousand1000/EG3D-projector#6]
我这边准备用eg3d，输入一张人脸图片，输出三维模型。
英伟达的人说可以参考您这项目：
https://github.com/NVlabs/eg3d/issues/60

我输入一张 fa.png图片，也拿到了图片对应的npy文件，
也运行：
python run_projector.py --outdir=projector_out --latent_space_type w  --network=networks/ffhq512-128.pkl --sample_mult=2  --image_path ./projector_test_data/fa.png --c_path ./projector_test_data/fa.npy

python run_projector.py --outdir=projector_out --latent_space_type w_plus  --network=networks/ffhq512-128.pkl --sample_mult=2  --image_path ./projector_test_data/fa.png --c_path ./projector_test_data/fa.npy

运行完毕，无报错，结果生成了，但是对应的模型没有找到。
下面是输出结果：
 root@MS-7996:/home/user/eg3d/EG3D-projector/eg3d/projector_out# tree
.
├── fa_w
│   ├── 0.png
│   ├── 100.png
│   ├── 200.png
│   ├── 300.png
│   ├── 400.png
│   └── fa_w.npy
└── fa_w_plus
    ├── 0.png
    ├── 100.png
    ├── 200.png
    ├── 300.png
    ├── 400.png
    └── fa_w_plus.npy

这是还要做啥操作吗？

**Comment by oneThousand1000** [comment]
你需要什么obj？请描述一下，至少给个图。
如果你说的是他们demo里面的https://nvlabs.github.io/eg3d/ 的Video 2
那个是用marching box生成的。
gen_samples.py 加上--shapes=True以后生成.mrc文件，然后使用eg3d官方的方法可视化：

We visualize our .mrc shape files with [UCSF Chimerax](https://www.cgl.ucsf.edu/chimerax/).

To visualize a shape in ChimeraX do the following:

Import the .mrc file with File > Open
Find the selected shape in the Volume Viewer tool
The Volume Viewer tool is located under Tools > Volume Data > Volume Viewer
Change volume type to "Surface"
Change step size to 1
Change level set to 10
Note that the optimal level can vary by each object, but is usually between 2 and 20. Individual adjustment may make certain shapes slightly sharper
In the Lighting menu in the top bar, change lighting to "Full"

**Comment by testouya** [comment]
https://www.bilibili.com/video/BV1v34y197TB/?spm_id_from=333.337.search-card.all.click&vd_source=c66c2e06b7cd16e8e963053c36cca1dd

就这个视频里的。

我是搞3d建模的，用3dmax，maya，blender什么的。我想要三维模型文件。

好比微软deep3dface一样，输入一个图片，输出一个三维的obj格式模型（不是c语言源码编译出来的目标文件，虽然他们后缀都一样）

您说的mrc是个啥？

**Comment by oneThousand1000** [comment]
官方没有obj模型生成。只有mrc文件。
在[l论文](https://nvlabs.github.io/eg3d/media/eg3d.pdf)的fig 有描述，‘’Shapes are iso-surfaces extracted from the density field using marching cubes.‘’

**Comment by oneThousand1000** [comment]
至于mrc怎么生成obj就不是我的专业范畴了，你可以找别的repo或者代码
