### ISSUE TITLE
Camera Parameters

### ISSUE THREAD

**Issue by mohitm1994** [oneThousand1000/EG3D-projector#9]
I have generated two files, dataset.json and camera.json. Both have different camera extrinsic. Which one should I use??

**Comment by oneThousand1000** [comment]
You should use the camera parameters that generated by [preprocess_cameras.py](https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_cameras.py), namely, the dataset.json.

**Comment by mohitm1994** [comment]
yes I used the files supplied in the official eg3d code. So for GAN inversion I convert **dataset.json** parameters to .npy format and then use it??

**Comment by oneThousand1000** [comment]
Yes, you're right. Load it by `json.load` and save it by `np.save`.

Or you can directly read camera parameters from dataset.json, just need some tiny modifications in loading camera parameters.

**Comment by mohitm1994** [comment]
Great, Thanks a lot again :)

**Comment by pfeducode** [comment]
> 

Hello, I would like to use images outside of the dataset to test the program. I am executing  https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_face_cameras.py  to generates dataset.json, the program shows that it needs to load cameras.json. May I ask what my execution steps are? The EG3D repository has changed the program file name, so I am a bit confused

**Comment by oneThousand1000** [comment]
> > 
> 
> Hello, I would like to use images outside of the dataset to test the program. I am executing https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_face_cameras.py to generates dataset.json, the program shows that it needs to load cameras.json. May I ask what my execution steps are? The EG3D repository has changed the program file name, so I am a bit confused

See https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_in_the_wild.py

**Comment by pfeducode** [comment]
> > > 
> > 
> > 
> > 您好，我想使用数据集之外的图像来测试程序。我正在执行https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_face_cameras.py生成dataset.json，程序显示需要加载cameras.json。请问我的执行步骤是什么？EG3D库改了程序文件名，有点迷糊
> 
> 请参见https://github.com/NVlabs/eg3d/blob/main/dataset_preprocessing/ffhq/preprocess_in_the_wild.py

I have successfully run it. Thank you for your answer
